### ISSUE TITLE
TODO list related to PR1072

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#1105]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
This issue is a TODO related to PR https://github.com/openfun/richie/pull/1072.

- [x] Configure the edx demo site so that a click to "Discover new" or to the logo in edx redirects the user to richie's search page ;
- [x] If the user is not logged-in, the message is blurred and a message is shown inviting the user to login first. It would be more enticing to keep the button active and send the user to login when he clicks on it ;
- [x] When a user logs in, he is sent back to the home page. He should be sent back to where he comes from ;
- [ ] ~If a course detail page is loaded and we wait sufficient time before trying to enroll, the xhr call will fail with a 403 because of CSRF protection. In this case, we should show a specific message inviting the user to reload the page and try again ;~
- [ ] ~When a user initiates a login from richie, he is sent to edx to authenticate himself before being redirected to richie. The user is then logged-in to richie but not to edX... so when he will enroll to a course and try to visit the course, he will be asked to login again... We must configure/adapt edx oauth2 to log the user to edx before redirecting him to richie ;~
- [x] Add an edX instance to our https://demo.richie.education site (e.g on https://edx.richie.education) ;
- [x] When going though the richie python social auth pipeline, which is configured by default in the sandbox, richie will create a new user if a user already exist with this username... for example, if a user with username "admin" exists on both sides, richie will generate a new user called "admin_{uuid}". This then leads to errors because the edX API identifies users on their username. We should customize the `create_user` step of the python social auth pipeline to raise and log an error if the user already exists. Not critical as this situation should not happen in production but it should not be possible by design as the communication with edX via the API relies on it...

**Comment by lunika** [comment]
> Configure the edx demo site so that a click to "Discover new" or to the logo in edx redirects the user to richie's search page ;

To change the `Discover New` link, the setting `FEATUREs.ENABLE_MKTG_SITE` must be set to true and the setting `MKTG_URLS` must be redefined. In the `COURSES` you can set the targeted URL.

```
FEATURES:
  ENABLE_MKTG_SITE: true

MKTG_URLS:
  COURSES: "https://www.fun-mooc.fr"
```
